cd /
sudo cp /home/orangepi/Documents/gps.service /etc/systemd/system/
sudo systemctl enable gps.service
sudo cp /home/orangepi/Documents/webservice.service /etc/systemd/system/
sudo systemctl enable webservice.service
sudo cp /home/orangepi/Documents/gpio.service /etc/systemd/system/
sudo systemctl enable gpio.service
sudo cp /home/orangepi/Documents/sql.service /etc/systemd/system/
sudo systemctl enable sql.service
sudo cp /home/orangepi/Documents/updater.service /etc/systemd/system/
sudo systemctl enable updater.service
sudo cp /home/orangepi/Documents/aux1.service /etc/systemd/system/
sudo systemctl enable aux1.service
sudo cp /home/orangepi/Documents/aux2.service /etc/systemd/system/
sudo systemctl enable aux2.service
sudo cp /home/orangepi/Documents/aux3.service /etc/systemd/system/
sudo systemctl enable aux3.service
sudo cp /home/orangepi/Documents/aux4.service /etc/systemd/system/
sudo systemctl enable aux4.service
sudo cp /home/orangepi/Documents/aux5.service /etc/systemd/system/
sudo systemctl enable aux5.service
sudo cp /home/orangepi/Documents/nfc.service /etc/systemd/system/
sudo systemctl enable nfc.service